hmcts/auto-shutdown

scripts/aks-auto-start.sh

https://tools.hmcts.net/jira/browse/DTSPO-11430
Remove logic that checks if cluster is already running
Removing this as the logic is identifying that clusters are already running when they are actually powered off, resulting in the clusters not starting up at all.
Example of issue in Auto-Start Workflow Run: https://github.com/hmcts/aks-auto-shutdown/actions/runs/3928173788/jobs/6715507054
```
[ ] Yes
[X] No
```

DTSPO-11430 -  Remove logic that checks if cluster is already running

---

scripts/aks-auto-start.sh

Updating code so tests to toffee/plum also effect the test env.
Changing the wait time for 30 seconds more to give cft-ithc addition time to allow plum to start.
```
[ ] Yes
[x] No
```

DTSPO-11424 testing plum/toffee on test cluster env

---

housekeeping.py

Correcting bug in housekeeping cleanup job. Script **should not** delete entries where end date is qual to current date.
```
[ ] Yes
[ x] No
```

removing equal to logic

---

.github/workflows/parsegithubissue.yaml

spam is happening in https://github.com/hmcts/aks-auto-shutdown/issues/30
untested but looks like it should work based on https://stackoverflow.com/a/71854535/4951015

Ignore renovate issue dashboard in parsing

---

.github/workflows/parsegithubissue.yaml

Fixes error on actions page:
> [parse](https://github.com/hmcts/aks-auto-shutdown/actions/runs/5713024936/job/15477628104)
The following actions uses node12 which is deprecated and will be forced to run on node16: andymckay/labeler@master. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
Also hopefully fixes renovate spam, I'll test this end 2 end after merging

Tweaks and remove archived action

---

.github/workflows/parsegithubissue.yaml
README.md
issues_list.json
scripts/aks/send-slack-message.sh
scripts/common/common-functions.sh

DTSPO-17194
Slack messages will now output slack "real names" rather than ambiguous GitHub usernames, making requesters easier to identify.
- Fixed a bug where nightly shutdown run would always be treated as the 23:00 run, even at 20:00.
- Removed dynamic link button which included issue ID, replaced with static "Review Request" button.
- JIRA reworded to Jira
- Approval comment now contains more information including a like to the review process.
- Marketplace actions upgrades.
- Some additional work is required to enable the conversion of approver name from GitHub to Slack.

DTSPO-17194 - GitHub -> Slack usernames

---

.github/workflows/parsegithubissue.yaml

Add separate step for exit after cancellation
`exit 0` in commit step did not take effect on recent run

DTSPO-15447 - Separate step for exit on cancel

---

.github/workflows/cancel-github-issue.yaml
issues_list.json

Run auto-start-stop script after a cancelled issue is removed from the json
Will only run if it's between 11pm and 7am

DTSPO-15447 - Run auto-start-stop after cancel

---

.github/workflows/parsegithubissue-pr.yaml
.github/workflows/parsegithubissue.yaml
scripts/aks/send-slack-message.sh

DTSPO-17194
adding logic for slack name conversions in the status field of the slack message.
Before:
After:
Setting exit codes to 1 instead of 0 to ensure pipeline cancels at the appropriate times.

DTSPO-17194 - adding logic for slack name conversions

---

issues_list.json

- Amends the pause shutdown end date for https://github.com/hmcts/auto-shutdown/issues/548 
- Confirmed with the requestor they only need it shutdown for 1 day

Amend pause shutdown dates

---

.github/workflows/appgateway-auto-shutdown.yaml
.github/workflows/appgateway-auto-start.yaml
scripts/aks/auto-start-stop.sh
scripts/appgateway/auto-start-stop.sh
scripts/common/common-functions.sh

DTSPO-18502
Following a number of tickets being raised, there was been an investigation into the skip logic within this repo. This PR addresses the following issues.
- Adds a second run at 23:00 to work with the already existing "stay on late" logic. This now matches the AKS clusters.
- Adds logging functionality to AppGateway workflow to aid with future troubleshooting.
- Conditional logic to set appropriate cluster_env variable, which now also supports ptlsbox, where it didn't before.
- Conditional logic to set appropriate application_gateway_env variable based on provided environment.
- Adds some initial logging to populate the log file, to aid future troubleshooting. This will expand over time. 
All of the above changes have been tested in the dev repo on the development branch - …

DTSPO-18502 - correcting found issues

---

scripts/appgateway/appgw_status.sh

The App Gateway status check was showing incorrect results following a [previous change ](https://github.com/hmcts/auto-shutdown/pull/680/files#diff-0797fff783f4accfc2e2b6fa56ced323cc4bc2a825604d6d4fcd10937c796a3dR37) made to the auto start / stop script.
This PR updates the status check to match the previous change and should resolve the false positive notification.

updating status check to match stop script

---

scripts/flexible-server/common-functions.sh

[DTSPO-18734](https://tools.hmcts.net/jira/browse/DTSPO-18734)
Teams have a need for replica DB to be `up` before their main DBs. This change is updating the order that things get pulled back from azure in, such that anything with `replica` is returned at the top of the list, hence being started before all other flex servers
i tested this locally and it returns replica dbs first now, this is because of using `reverse`

DTSPO-18734: Allow replicas to be started first

---

scripts/flexible-server/auto-start-stop.sh
scripts/flexible-server/common-functions.sh

[DTSPO-18841](https://tools.hmcts.net/jira/browse/DTSPO-18841)
Using 'az graph' instead of 'az resource' to improve script efficiency as graph works across all subscriptions we won't need to loop through all subscriptions individually.
During testing this has cut the run time down from +42 minutes to just over 1 minute.
Following successful testing within this repo, I will roll this out to the remaining scripts to maintain consistency.
- Tested in auto-shutdown-dev repo
Before
After

DTSPO-18841 - az graph for Flexible servers.

---

.github/workflows/aks-auto-shutdown.yaml
.github/workflows/aks-auto-start.yaml
scripts/aks/auto-shutdown-status.sh
scripts/aks/common-functions.sh

Updating AKS cluster status check to be in line with other auto-shutdown resources. 
Notifications are now sent to [#auto-shutdown-status](https://moj.enterprise.slack.com/archives/C07CL9KJHUN)
Tested in dev environment
To be monitored

DTSPO-19088 - Adding new AKS status script

---

.github/workflows/aks-auto-shutdown.yaml
.github/workflows/aks-auto-start.yaml
scripts/aks/auto-shutdown-status.sh

- Adding production flag to include PTL clusters (there were previously included in the old scripts)
- Correcting status script to avoid sending errors where clusters are expected to not be shutdown.
Tested in development environment
To be monitored

DTSPO-19088 - Correcting AKS Cluster status script

---

.github/workflows/aks-manual-shutdown.yaml
.github/workflows/aks-manual-start.yaml
scripts/aks/common-functions.sh
scripts/aks/manual-start-stop.sh

DTSPO-19088
- Renaming PROJECT to SELECTED_AREA as this makes more sense.
- Removing option to select specific cluster as this is not used and introduces unnecessary complexity.
- Added new to_lowercase function to common scripts
- Updated manual start / stop script to work with new graph functions
- Tested in dev repo 
- To be monitored

DTSPO-19088 - Updating manual AKS script

---

scripts/common/common-functions.sh

This was working but missed the change that required these files to go into a new dir, had this created locally so it worked but when running remotely the `status` dir was missing, causing:
````scripts/common/common-functions.sh: line 75: status/flexible-server_status_updates_stop.json: No such file or directory
jq: error: Could not open file status/flexible-server_status_updates_stop.json: No such file or directory
JSON file updated successfully.```
This change adds the dir so the file can be built correctly

Update to fix json file storage

---

scripts/aks/send-slack-message.sh
scripts/common/common-functions.sh

[DTSPO-18652](https://tools.hmcts.net/jira/browse/DTSPO-18652)
- Creating new get_current_date_time function for slack message process to allow the use of get_current_date in weekend logic.
- Expanding is_late_night_run() function condition to include early hours of the. morning as "late night".
- Reducing unnecessary logging making troubleshooting more difficult.
- Adding break clause to while look in is_weekend_in_range() (once a weekend has been found, there is no need to continue the loop).
- Moving late night and weekend day function calls to outside of the read issue loop as this only needs to occur once.
Tested multiple scenarios in the dev environment.
- [ x ] commit messages are meaningful and follow good commit message guidelines
- [ x ] README and other documentation has been …

DTSPO-18652 - Adding weekend logic fix

---

scripts/aks/common-functions.sh
scripts/vm/common-functions.sh
scripts/vm/vmstatus.sh

[DTSPO-23335](https://tools.hmcts.net/jira/browse/DTSPO-23335)
The result of the status check for the VM 'CTS' was appearing with empty values in the auto-shutdown-status channel. This created an unhelpful status message and didn't inspire confidence for the rest of the checks. See below
After investigation, it was found that the existing MS Graph query was retrieving public key information by default. In the case of this specific VM, the key data contained characters that invalidated the json payload. Due to this, the scripts were unable to retrieve information such as resource group, name, environment, business area, start up mode or VM state.  This also explains why this was occurring for this VM, and not others.
This PR makes the Graph query more specific to only retrieve the …

DTSPO-23335 - Modify Graph query to target specific fields

---

.github/workflows/flexibleserver-auto-shutdown.yaml
.github/workflows/sqlmi-auto-shutdown.yaml
.github/workflows/storage-sftp-auto-disable.yaml

N/A
Whole investigating a lot of unexpected output in the auto-shutdown-status channel, I noticed that some resources do not have a scheduled 23:00 run.

Adding 23:00 run to more resources

---

.github/workflows/flexibleserver-auto-start.yaml

DTSPO-23913
Setting flexserver to start before VM's as services trying to connect to DB's at startup may be left in a failed state if connections fail.

DTSPO-23913 - setting flexserver to start before VM's

---

azure-pipeline-start-elasticsearch.yml

https://tools.hmcts.net/jira/browse/DTSPO-24698
- Pointed out in the above ticket that Elasticsearch failed to start yesterday morning and was not retried until near 4pm. (Should be every one hour)
- Adding `always: true` to pipeline to make sure it always runs on cron schedule

Set Elasticsearch pipeline to always start

---

.github/workflows/vmss-auto-shutdown.yaml
.github/workflows/vmss-auto-start.yaml

See [DTSPO-23901](https://tools.hmcts.net/jira/browse/DTSPO-23901)
Enable cron triggers for VM Scale Sets auto shutdown/startup workflows. This is to be merged only after these new workflows has been end to end tested.
- Unit testing has been done (manual). The VM Scale Sets auto-start-stop.sh has been manually tested.
- End to end testing must be done before merging this PR.

Enable cron triggers for VM Scale Sets auto shutdown/startup workflows

---

scripts/vmss/common-functions.sh
scripts/vmss/manual-start-stop.sh
scripts/vmss/vmss-status.sh

See [DTSPO-23901](https://tools.hmcts.net/jira/browse/DTSPO-23901)
Bugfixes in the VM Scale Sets auto shutdown and startup, vmss status and manual start/stop scripts
Tested locally in a terminal, az commands echoed to the screen.

Fix the auto startup/shutdown scripts for VM Scale Sets
