hmcts/auto-shutdown

- .github/CODEOWNERS
- .github/workflows/aks-auto-shutdown.yaml
- .github/workflows/aks-auto-start.yaml
- scripts/aks-auto-shutdown.sh
- scripts/aks-auto-start.sh
[DTSPO-11424](https://tools.hmcts.net/jira/browse/DTSPO-11424)
Add shutdown and start scripts with github action workflows
Add codeowners file and assign to Platform Operations
```
[ ] Yes
[X] No
```
> DTSPO-11424: Add shutdown and start scripts with github action workflows

- scripts/aks-auto-start.sh
[DTSPO-11424](https://tools.hmcts.net/jira/browse/DTSPO-11424)
Add tests to aks-auto-shutdown.sh
```
[ ] Yes
[X] No
```
> DTSPO-11424: Add tests to aks-auto-shutdown.sh

- README.md
Update README with brief description of repository.
```
[ ] Yes
[X] No
```
> DTSPO-11424 - Update README.md

- .github/workflows/aks-auto-shutdown.yaml
- .github/workflows/aks-auto-start.yaml
Shutdown sandbox over the weekend (as requested by Bruce Rawstorne)
```
[ ] Yes
[X] No
```
> DTSPO-11424 - Shutdown SBOX clusters on weekends

- .github/workflows/aks-auto-start-dry-run.yaml
- scripts/aks-auto-start-dry-run.sh
Adding dry run of aks auto start script to try fix failing tests
```
[ ] Yes
[X] No
```
> DTSPO-11424 - Add auto start dry run script

- scripts/aks-auto-start-dry-run.sh
Add retry attempts when connecting to test app
```
[ ] Yes
[X] No
```
> DTSPO-11424 - Add retry attempts when connecting to test app

- scripts/aks-auto-start.sh
Add Retries to Tests
```
[ ] Yes
[X] No
```
> DTSPO-11424 - Add Retries to Tests

- scripts/aks-auto-start.sh
Remove set -e
```
[ ] Yes
[X] No
```
> DTSPO-11424 - Remove set -e

- .github/workflows/aks-auto-start.yaml
[DTSPO-11424](https://tools.hmcts.net/jira/browse/DTSPO-11424)
Update Schedule to Start Clusters at 6:30am
```
[ ] Yes
[X] No
```
> DTSPO-11424 - Update Schedule to Start Clusters at 6:30am

- scripts/aks-auto-start.sh
> Increase wait time to 10 min

- scripts/aks-auto-start.sh
https://tools.hmcts.net/jira/browse/DTSPO-11432
Adding additional channels to be notified when clusters start-up
```
[ ] Yes
[x] No
```
> Dtspo 11432 add notification to aks monitor

- .github/workflows/aks-manual-start.yaml
https://tools.hmcts.net/jira/browse/DTSPO-12179
Make Cluster Option 'All' default
```
[ ] Yes
[X] No
```
> DTSPO-12179 - Make Cluster Option 'All' default

- .github/workflows/aks-manual-start.yaml
https://tools.hmcts.net/jira/browse/DTSPO-12179
Update Github Workflow
```
[ ] Yes
[X] No
```
> DTSPO-12179 - Update Github Workflow

- .github/workflows/aks-manual-shutdown.yaml
- scripts/aks-manual-shutdown.sh
https://tools.hmcts.net/jira/browse/DTSPO-12179
Add Manual Shutdown
```
[ ] Yes
[X] No
```
> DTSPO-12179 - Add Manual Shutdown

- .github/workflows/keepalive.yaml
> Create a pipeline to keep scheduled jobs active

- .github/workflows/aks-auto-shutdown.yaml
[DTSPO-13971](https://tools.hmcts.net/jira/browse/DTSPO-13971)
Change schedule to run every day of the week
```
[ ] Yes
[X] No
```
> DTSPO-13971 - Change schedule to run every day of the week

- housekeeping.py
Adding missing house keeping script from test repo (aks-auto-shutdown-releases)
```
[ ] Yes
[x ] No
```
> adding housekeeping script

- .github/ISSUE_TEMPLATE/skip-auto-shutdown-request.yaml
- .github/workflows/aks-auto-shutdown.yaml
- file_handling.py
- issues_list.json
- scripts/aks-auto-shutdown-status.sh
- scripts/aks-auto-shutdown.sh
DTSPO-13971
- Adding better start / end date description
- Adding "--no-wait" flag to aks shutdown command to increase script efficiency to avoid authentication timeouts.
- Adding cluster status check script to provide a summary of clusters states post script. Built-in delay of 10 minutes to give clusters time to stop.
- Removing test entry from json
```
[ ] Yes
[x ] No
```
> DTSPO-13971 Improvements

- issues_list.json
> cancelled preview skip for 28th July

- .github/workflows/aks-auto-shutdown.yaml
- .github/workflows/aks-auto-start.yaml
N/A
Setting cron times to match current UK timezone of BST
```
[ ] Yes
[ x] No
```
> setting cron time to match UK timezone (BST)

- .github/workflows/aks-auto-shutdown.yaml
- .github/workflows/aks-auto-start.yaml
> renaming workflow names

- .github/workflows/vm-auto-start.yaml
> Update vm auto start up script.

- .github/workflows/parsegithubissue.yaml
- requirements.txt
adding requirements.txt
```
[ ] Yes
[x] No
```
> adding requirements.txt

- issues_list.json
removing test entries
```
[ ] Yes
[ x] No
```
> removing test entries

- issues_list.json
> removing test entry

- .github/workflows/parsegithubissue.yaml
- Lowering "High Cost" label trigger value to £1,000
- Adding bold formatting to value
```
[ ] Yes
[ x] No
```
> lowering 'High Cost' trigger value. Bolding value

- .github/workflows/flexibleserver-auto-shutdown.yaml
- .github/workflows/flexibleserver-auto-start.yaml
- scripts/flexible-server/auto-shutdown.sh
- scripts/flexible-server/auto-start.sh
- scripts/flexible-server/flexserverstatus.sh
- scripts/vm/auto-shutdown.sh
- scripts/vm/auto-start.sh
- scripts/vm/vmstatus.sh
> autoshutdown flexible server

- issues_list.json
DFPL-1561
- Remove exclusion as out of hours release (CHG5013243) was cancelled
```
[ ] Yes
[X] No
```
> DFPL-1561: Cancel exclusion as out of hours release cancelled

- scripts/appgateway/auto-shutdown.sh
> enable auto shutdown for appgateway in all  non-prod envs

- scripts/appgateway/appstatus.sh
- scripts/appgateway/auto-shutdown.sh
- scripts/appgateway/auto-start.sh
> enable debugging

- scripts/flexible-server/auto-shutdown.sh
> enable autoshutdown in sbox env for flexible server

- scripts/cost-calculator.py
> reducing retry count to 5

- scripts/vm/auto-shutdown.sh
https://tools.hmcts.net/jira/browse/DTSPO-14603
Uncommented out the hash from the code
```
[ ] Yes
[x] No
```
> DTSPO-14603: Uncommented hash from code

- scripts/appgateway/appstatus.sh
- scripts/appgateway/auto-shutdown.sh
- scripts/appgateway/auto-start.sh
- scripts/flexible-server/auto-shutdown.sh
> enable flexserver across all nonprod envs

- .github/workflows/manual-start.yaml
- issues_list.json
- scripts/appgateway/manual-start.sh
- scripts/flexible-server/manual-start.sh
> Create a pipeline to manually start resources in an ENV

- scripts/flexible-server/auto-shutdown.sh
> Update flexibleserver auto-shutdown script

- .github/workflows/storage-sftp-auto-enable.yaml
> fix file name typo

- issues_list.json
> Revert test change

- scripts/aks/auto-start.sh
> Refactor auto start script

- scripts/aks/auto-shutdown.sh
- scripts/aks/auto-start.sh
- scripts/aks/common-functions.sh
- Tested them locally, Merging them before further changes on on demand startup
> Reuse methods between start and shutdown

- scripts/aks/auto-shutdown.sh
- scripts/aks/auto-start.sh
- scripts/aks/common-functions.sh
- scripts/aks/manual-start-stop.sh
> consistent clustername across scripts

- .github/workflows/aks-auto-shutdown.yaml
- .github/workflows/aks-auto-start.yaml
- .github/workflows/appgateway-auto-shutdown.yaml
- .github/workflows/appgateway-auto-start.yaml
- .github/workflows/flexibleserver-auto-shutdown.yaml
- .github/workflows/flexibleserver-auto-start.yaml
- .github/workflows/sqlmi-auto-shutdown.yaml
- .github/workflows/sqlmi-auto-start.yaml
- .github/workflows/storage-sftp-auto-disable.yaml
- .github/workflows/storage-sftp-auto-enable.yaml
- .github/workflows/storage-sftp-check-status.yml
- .github/workflows/vm-auto-shutdown.yaml
- .github/workflows/vm-auto-start.yaml
N/A
updating crons to reflect new timezone
> updating crons to reflect new timezone

- .github/workflows/aks-auto-shutdown.yaml
- .github/workflows/aks-auto-start.yaml
- scripts/aks/auto-shutdown-status.sh
- scripts/aks/auto-start-stop.sh
DTSPO-15113
Re-factor aks status script
> Dtspo 15113

- issues_list.json
> change end date

- scripts/aks/auto-start-stop.sh
DTSPO-15113
Change mode to stop
> change mode to stop

- .github/workflows/aks-auto-start.yaml
> remove argument

- .github/workflows/aks-auto-start.yaml
Reverts hmcts/auto-shutdown#204
> Revert "remove argument"

- scripts/aks/auto-start-stop.sh
DTSPO-15113
Revert PR 202 https://github.com/hmcts/auto-shutdown/pull/202/files
> revert PR 202

- issues_list.json
- scripts/aks/common-functions.sh
- scripts/aks/resource-details.sh
- scripts/appgateway/auto-shutdown.sh
- scripts/file_handling.py
- scripts/flexible-server/auto-shutdown.sh
- scripts/housekeeping.py
- scripts/sqlmi/auto-shutdown.sh
- scripts/vm/auto-shutdown.sh
> Alignging var names to generic

- .github/ISSUE_TEMPLATE/ondemand-env-startup-request.yaml
- scripts/aks/common-functions.sh
- scripts/file_handling.py
> Add on demand env start up request

- scripts/file_handling.py
- [ x] Does this PR introduce a breaking change
> fix pop when it doesnt exist

- scripts/file_handling.py
> use pop so that it doesnt exist in generated json

- issues_list.json
https://github.com/hmcts/auto-shutdown/issues/253 Revrting 
Update issues_list.json
> Reverting 253 shutdown 

- scripts/common/common-functions.sh
- scripts/sqlmi/auto-start-stop.sh
> parameter wrong

- issues_list.json
DTSPO-15113
Update issues list
> update issues list

- .github/workflows/aks-auto-shutdown.yaml
- .github/workflows/aks-auto-start.yaml
- .github/workflows/appgateway-auto-shutdown.yaml
- .github/workflows/appgateway-auto-start.yaml
- .github/workflows/flexibleserver-auto-shutdown.yaml
- .github/workflows/flexibleserver-auto-start.yaml
- .github/workflows/housekeeping_aks_issuejson.yaml
- .github/workflows/sqlmi-auto-shutdown.yaml
- .github/workflows/sqlmi-auto-start.yaml
- .github/workflows/storage-sftp-auto-disable.yaml
- .github/workflows/storage-sftp-auto-enable.yaml
- .github/workflows/storage-sftp-check-status.yml
- .github/workflows/vm-auto-shutdown.yaml
- .github/workflows/vm-auto-start.yaml
n/a
updating cron schedules following clock change
> updating cron schedules following clock change

- .github/workflows/parsegithubissue.yaml
- scripts/remove_entry.py
Add autoshutdown revert steps and script
> DTSPO-15447 - Auto shutdown revert

- .github/workflows/parsegithubissue.yaml
Move checkout so cancel script can be found
Currently causing an error when cancel label added
> DTSPO-15447 - move checkout

- scripts/remove_entry.py
Fix typo in repo name in script
> DTSPO-15447 - fix typo

- README.md
Add guidance on how to cancel to the readme
> DTSPO-15447 - Add cancel info to readme

- .github/ISSUE_TEMPLATE/ondemand-env-startup-request.yaml
- .github/ISSUE_TEMPLATE/skip-auto-shutdown-request.yaml
- .github/workflows/parsegithubissue.yaml
- scripts/file_handling.py
DTSPO-17195
- Updating issue parser to a version that uses nodejs 20 instead of v16 as this will be deprecated.
- Removing label action from marketplace as it does not support nodejs 20. This has been replaced with a more lightweight solution which uses the GitHub API instead.
> DTSPO-17195 - Updating issue parser

- .github/workflows/parsegithubissue-pr.yaml
- README.md
Replace title of slack message with PR number
Was showing as `PR-$issue_number` instead of `PR-pull_request_number`
> Fix typo in slack message title

- .github/ISSUE_TEMPLATE/2-ondemand-env-startup-request.yaml
- .github/ISSUE_TEMPLATE/3-skip-auto-shutdown-request.yaml
I was just having a peak at this and I think these read better, thoughts?
> Copy editing of form

- scripts/appgateway/appgw_status.sh
- scripts/appgateway/auto-start-stop.sh
- scripts/appgateway/common-functions.sh
- scripts/flexible-server/common-functions.sh
- scripts/flexible-server/flexserverstatus.sh
- scripts/sqlmi/auto-start-stop.sh
- scripts/sqlmi/common-functions.sh
- scripts/sqlmi/sqlmistatus.sh
- scripts/vm/auto-start-stop.sh
- scripts/vm/common-functions.sh
- scripts/vm/vmstatus.sh
Update status check scripts to include the skip check from main stop/start scripts to reduce false positives
> Update status check scripts to include the skip check from main stop/start scripts to reduce false positives

- scripts/flexible-server/manual-start.sh
> fix reference to source script in flex servers

- .github/workflows/vm-auto-shutdown.yaml
- scripts/common/common-functions.sh
- scripts/flexible-server/auto-start-stop.sh
- scripts/vm/auto-start-stop.sh
- scripts/vm/vmstatus.sh
https://tools.hmcts.net/jira/browse/DTSPO-18284
Updating VM scripts to use deallocate instead of stop for cost savings, requires update of common function that checks for SKIP status
> Updating VM scripts to use deallocate instead of stop for cost savings

- scripts/aks/auto-start-stop.sh
- scripts/appgateway/auto-start-stop.sh
- scripts/blob-storage/disable_sftp.sh
- scripts/common/common-functions.sh
- scripts/flexible-server/auto-start-stop.sh
- scripts/sqlmi/auto-start-stop.sh
- scripts/vm/auto-start-stop.sh
> Dtspo 18502

- scripts/aks/auto-start-stop.sh
- scripts/appgateway/auto-start-stop.sh
- scripts/blob-storage/disable_sftp.sh
- scripts/common/common-functions.sh
- scripts/flexible-server/auto-start-stop.sh
- scripts/sqlmi/auto-start-stop.sh
- scripts/vm/auto-start-stop.sh
Reverts hmcts/auto-shutdown#658
> Revert "Dtspo 18502"

- .github/workflows/aks-auto-shutdown.yaml
- .github/workflows/aks-auto-start.yaml
- .github/workflows/appgateway-auto-shutdown.yaml
- .github/workflows/appgateway-auto-start.yaml
- .github/workflows/flexibleserver-auto-shutdown.yaml
- .github/workflows/flexibleserver-auto-start.yaml
- .github/workflows/sqlmi-auto-shutdown.yaml
- .github/workflows/sqlmi-auto-start.yaml
- .github/workflows/vm-auto-shutdown.yaml
- .github/workflows/vm-auto-start.yaml
- scripts/aks/auto-start-stop.sh
- scripts/aks/common-functions.sh
- scripts/appgateway/auto-start-stop.sh
- scripts/appgateway/common-functions.sh
- scripts/blob-storage/common-functions.sh
- scripts/blob-storage/disable_sftp.sh
- scripts/blob-storage/enable_sftp.sh
- scripts/common/common-functions.sh
- scripts/flexible-server/auto-start-stop.sh
- scripts/flexible-server/common-functions.sh
- scripts/sqlmi/auto-start-stop.sh
- scripts/sqlmi/common-functions.sh
- scripts/vm/auto-start-stop.sh
- scripts/vm/common-functions.sh
DTSPO-18506
- Adding logic to determine if scripts are running in development environment or live.
- Updating AKS scripts to use common ts_echo_color function.
> DTSPO-18506 - development env logic

- scripts/appgateway/auto-start-stop.sh
> syntax correction

- .github/workflows/aks-auto-shutdown.yaml
- .github/workflows/aks-auto-start.yaml
- scripts/aks/auto-start-stop.sh
- scripts/common/common-functions.sh
- scripts/common/log-output.sh
N/A
- Adding new log function to aid troubleshooting.
- Only enabled on AKS scripts for now, will expand to other scripts after issues have been sorted.
> New Log function

- scripts/common/common-functions.sh
n/a
adding debug logging for tonights run
> adding debug logging for tonights run

- .github/workflows/flexibleserver-auto-shutdown.yaml
- .github/workflows/flexibleserver-auto-start.yaml
- .github/workflows/sqlmi-auto-shutdown.yaml
- .github/workflows/sqlmi-auto-start.yaml
- .github/workflows/storage-sftp-auto-disable.yaml
- .github/workflows/storage-sftp-auto-enable.yaml
- .github/workflows/vm-auto-shutdown.yaml
- .github/workflows/vm-auto-start.yaml
- scripts/appgateway/auto-start-stop.sh
- scripts/blob-storage/disable_sftp.sh
- scripts/blob-storage/enable_sftp.sh
- scripts/flexible-server/auto-start-stop.sh
- scripts/flexible-server/common-functions.sh
- scripts/sqlmi/auto-start-stop.sh
[DTSPO-18502](https://tools.hmcts.net/jira/browse/DTSPO-18502)
- Adding logging feature to remaining resources.
- Correcting flexible server skip input vars.
- Adding if statements around environment vars on remaining resources.
Fully tested in https://github.com/hmcts/auto-shutdown-dev
> DTSPO-18502 - Adding logging feature to remaining resources & Flexible Server bug fix

- scripts/flexible-server/flexserverstatus.sh
Quick bugfix for status checks of Flexible Postgres servers
> Updating status script to match start/stop

- scripts/flexible-server/auto-start-stop.sh
- scripts/flexible-server/common-functions.sh
[DTSPO-18841](https://tools.hmcts.net/jira/browse/DTSPO-18841)
Comment updates
> DTSPO-18841 - updating flexible server comments

- .github/workflows/flexibleserver-auto-shutdown.yaml
- .github/workflows/flexibleserver-auto-start.yaml
- scripts/common/common-functions.sh
- scripts/flexible-server/auto-start-stop.sh
- scripts/flexible-server/common-functions.sh
- scripts/flexible-server/flexserverstatus.sh
[DTSPO-18841](https://tools.hmcts.net/jira/browse/DTSPO-18841)
- Split startup and stop jobs out by env for Flexible servers (this should avoid any future timeouts)
- Moved Flexible server check script to az graph
- Adding conditional statement to wait times and status checker for dev env.
> DTSPO-18841 - start / stop by env

- .github/workflows/appgateway-auto-shutdown.yaml
- .github/workflows/appgateway-auto-start.yaml
- .github/workflows/flexibleserver-auto-shutdown.yaml
- .github/workflows/flexibleserver-auto-start.yaml
- .github/workflows/sqlmi-auto-shutdown.yaml
- .github/workflows/sqlmi-auto-start.yaml
- .github/workflows/storage-sftp-auto-disable.yaml
- .github/workflows/storage-sftp-auto-enable.yaml
- scripts/appgateway/appgw_status.sh
- scripts/appgateway/auto-start-stop.sh
- scripts/appgateway/common-functions.sh
- scripts/blob-storage/common-functions.sh
- scripts/blob-storage/disable_sftp.sh
- scripts/blob-storage/enable_sftp.sh
- scripts/flexible-server/auto-start-stop.sh
- scripts/flexible-server/common-functions.sh
- scripts/flexible-server/flexserverstatus.sh
- scripts/sqlmi/auto-start-stop.sh
- scripts/sqlmi/common-functions.sh
- scripts/sqlmi/sqlmistatus.sh
Transitioning to MS Graph for efficiency gains and simplified code.
- Flexible Server
- AppGateway
- SQL MI
- Blob storage
TO be completed in follow up PR
- AKS transition to MS graph
- VM transition to MS graph
- Status checks to be updated to match changes.
Tested in auto-shutdown-dev
Changes to be monitored
> DTSPO-19088 - Transition to MS Graph

- scripts/appgateway/appgw_status.sh
- scripts/appgateway/common-functions.sh
- scripts/sqlmi/sqlmistatus.sh
- Updating AppGateway to use OperationalState rather than ProvisioningState
- Adding logic to check for empty results to SQL MI resources (as we currently have no resources enrolled in auto-shutdown)
- Correcting AppGateway function call within status check script.
Tested locally
Actions to be monitored
> DTSPO-19088 - Update

- .github/workflows/aks-auto-shutdown.yaml
- .github/workflows/appgateway-auto-shutdown.yaml
- .github/workflows/flexibleserver-auto-shutdown.yaml
- .github/workflows/parsegithubissue.yaml
- .github/workflows/vm-auto-shutdown.yaml
https://tools.hmcts.net/jira/browse/DTSPO-19265
- Re-enable shutdown jobs after creating a test issue that processed correctly
- Changes `'` to `"` in inline bash script to ensure vars are parsed correctly. Should fix error: unexpected EOF while looking for matching `"'
- https://github.com/hmcts/auto-shutdown/actions/runs/11180379007/job/31081980888
> DTSPO-19265 investigate auto-shutdown

- .github/workflows/appgateway-auto-start.yaml
- scripts/common/common-functions.sh
https://tools.hmcts.net/jira/browse/DTSPO-19297
- Enabling printing slack response to troubleshoot jobs
- Setting `DEV_ENV` to true in app gateway auto start job to prevent running any real start commands
- Removing condition from job so that status check runs even in dev mode - This appears to be where the issue is.
- Will revert immediately after testing.
- Attempted to test in the dev repo but can't replicate the issue
> DTSPO-19297 Troubleshoot failing jobs

- scripts/common/common-functions.sh
- Adding more logging to slack notification for troubleshooting
> Update slack notification with more logging

- .github/workflows/appgateway-auto-start.yaml
- scripts/common/common-functions.sh
https://tools.hmcts.net/jira/browse/DTSPO-19297
- Reverting changes made in previous PRs for troubleshooting
> DTSPO-19297 Reverting changes

- .github/ISSUE_TEMPLATE/1-pull-request-template.md
- .github/ISSUE_TEMPLATE/2-ondemand-env-startup-request.yaml
- .github/ISSUE_TEMPLATE/3-skip-auto-shutdown-request.yaml
- .github/workflows/parsegithubissue-pr.yaml
- .github/workflows/parsegithubissue.yaml
- README.md
- scripts/aks/message-template.json
- scripts/aks/resource-details.sh
- scripts/aks/send-slack-message.sh
- scripts/file_handling.py
https://tools.hmcts.net/jira/browse/DTSPO-18851
- Adds additional field for `Team/Application Name` so that it is easy to identify who the request is for
> Dtspo 18851 Add Team Name

- .github/workflows/parsegithubissue-pr.yaml
- .github/workflows/parsegithubissue.yaml
- Currently when a `'` is present in an issue it causes the job to fail - https://github.com/hmcts/auto-shutdown/actions/runs/11180379007 
- This attempts to better handle these situations by removing any `'` prior to processing
- Tested in PR by updating default value to include `'`
> Handle issues containing single quotes better

- scripts/aks/auto-start-stop.sh
- scripts/aks/common-functions.sh
Correcting error in script where subscription flag is missing from CLI command.
Tested in dev repo
> DTSPO-19088 - AKS - adding subscription flag

- .github/workflows/aks-auto-shutdown.yaml
- .github/workflows/aks-auto-start.yaml
DTSPO-19088
Increasing wait time between starting clusters and doing checks.
N/A
> DTSPO-19088 - increasing wait time

- .github/workflows/auto-stop-status-check.yaml
Current error is because VMs now use deallocate instead of stop
> Fix VM status stop/deallocate error

- .github/workflows/auto-start-status-check.yaml
- .github/workflows/auto-stop-status-check.yaml
Still just keeping this on a branch to test it working properly before pushing to master, push to origin was missed originally
> Update to push to remote branch

- scripts/common/common-functions.sh
- scripts/vm/auto-start-stop.sh
- scripts/vm/common-functions.sh
- scripts/vm/vmstatus.sh
- VM auto start / stop script updated for MS graph
- Adding tag_not_set defaults for get_vm_details function
- Adjusting power state case statements to work with values from ms graph
- Moving lowercase function to common functions
Tested in Development Environment
To be monitored
> DTSPO-19088 - updating VM script to work with ms graph

- .github/workflows/auto-start-status-check.yaml
- .github/workflows/auto-stop-status-check.yaml
[DTSPO-18443](https://tools.hmcts.net/jira/browse/DTSPO-18443)
Shown that this is working ideally in https://github.com/hmcts/auto-shutdown/compare/master...testing-json-file-updates-stop in terms of json structure and POC
Now this can push the updates to master so we can read these files
> DTSPO-18443: Update after test to now push to master

- scripts/vm/auto-start-stop.sh
- scripts/vm/common-functions.sh
Updating VM_ID variable to use correct format
> DTSPO-19088 - Updating VM_ID variable to use correct format

- scripts/blob-storage/sftp-check-status.sh
DTSPO-19088
Removing subscription selection from SFT status check script
Tested in dev
> DTSPO-19088 - removing subscription selection from SFT status check script

- .github/workflows/add-to-dashboard.yaml
- .github/workflows/cancel-github-issue.yaml
- Auto shuttdown dashboard view 
Tested in auto-shutdown-dev https://github.com/orgs/hmcts/projects/29/views/2
> add workflow for auto shutdown dashboard view

- .github/ISSUE_TEMPLATE/3-skip-auto-shutdown-request.yaml
n/a
Making date selector description more useful
> Update - making date selector description more useful

- azure-pipeline-start-elasticsearch.yml
- scripts/vm/restart-es-service.sh
- Pipeline was failing with `/azure-pipeline-start-elasticsearch.yml (Line: 21, Col: 3): A mapping was not expected`
- Removed stages and other parts that are not needed
> Fix elasticsearch workflow

- .github/workflows/aks-auto-start.yaml
- .github/workflows/appgateway-auto-start.yaml
- .github/workflows/auto-start-status-check.yaml
- .github/workflows/flexibleserver-auto-start.yaml
- .github/workflows/sqlmi-auto-start.yaml
- .github/workflows/storage-sftp-auto-enable.yaml
- .github/workflows/vm-auto-start.yaml
temporary disable auto start during change freeze period
> temporary disable auto start during change freeze period

- .github/workflows/manual-start-stop.yaml
- scripts/aks/common-functions.sh
- scripts/appgateway/common-functions.sh
- scripts/flexible-server/common-functions.sh
- scripts/vm/common-functions.sh
- scripts/vm/manual-start-stop.sh
DTSPO-23040
- Adding VM step to manual start job
- Dealing with case sensitive issues in business area tags
Tested in dev
> DTSPO-23040 -  Adding VM step to manual start job

- .github/workflows/aks-auto-start.yaml
- .github/workflows/appgateway-auto-start.yaml
- .github/workflows/auto-start-status-check.yaml
- .github/workflows/flexibleserver-auto-start.yaml
- .github/workflows/sqlmi-auto-start.yaml
- .github/workflows/storage-sftp-auto-enable.yaml
- .github/workflows/vm-auto-start.yaml
Reverting back to usual schedule.
> Revert "temporary disable auto start during change freeze period"

- issues_list.json
Updated date according to Linda's request on Platops Channel.
> Updated PRL auto shutdown date

- .github/ISSUE_TEMPLATE/3-skip-auto-shutdown-request.yaml
See [DTSPO-21968](https://tools.hmcts.net/jira/browse/DTSPO-21968)
fix description limitation of 200 character issue 
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
Please list any issues found during testing and how they were resolved:
N/A
Please provide the steps required to deploy these changes to Azure.
Please add any other information that is important to this PR, such as screenshots, logs, or links to other related PRs.
> DTSPO-21968- Fix description limitation issue on template

- .github/workflows/manual-start-stop.yaml
- .github/workflows/vmss-auto-shutdown.yaml
- .github/workflows/vmss-auto-start.yaml
See [PROJ-23901](https://tools.hmcts.net/jira/browse/PROJ-23901)
Add auto shutdown and auto startup workflows for Virtual Machine Scale Sets.
Testing to be done together with the auto shutdown/startup shell scripts for VMSS. The cron triggers are disabled for now.
> Dtspo 23901 vmss auto startup workflow

- scripts/vmss/common-functions.sh
https://tools.hmcts.net/jira/browse/DTSPO-23901
Adding the DCD-CNP-QA & DCD-CNP-DEV subscriptions to the VMSS script for IDAM.
Tags have been set to **autoShutdown: false** to not shutdown demo & perftest. VMSS, these are to be changed at a later date by the IDAM team.
Tags have been set to **autoShutdown: true** to shutdown idam-sandbox, idam-ithc and idam-preview VMSS
Scripts have been tested locally and shutdown in sandbox, smoke test all done by the IDAM team.
> add dcd-cnp-qa & dcd-cnp-dev subs to vmss

- .github/workflows/auto-start-status-check.yaml
- .github/workflows/auto-stop-status-check.yaml
- .github/workflows/json-file-cleardown.yaml
Bot cannot update master properly, matching other workflows that do it
> Bot cannot update master properly, matching other workflows that do it

- .github/workflows/aks-auto-shutdown.yaml
- .github/workflows/aks-auto-start.yaml
- .github/workflows/appgateway-auto-shutdown.yaml
- .github/workflows/appgateway-auto-start.yaml
- .github/workflows/auto-start-status-check.yaml
- .github/workflows/auto-stop-status-check.yaml
- .github/workflows/flexibleserver-auto-shutdown.yaml
- .github/workflows/flexibleserver-auto-start.yaml
- .github/workflows/housekeeping_aks_issuejson.yaml
- .github/workflows/json-file-cleardown.yaml
- .github/workflows/sqlmi-auto-shutdown.yaml
- .github/workflows/sqlmi-auto-start.yaml
- .github/workflows/storage-sftp-auto-disable.yaml
- .github/workflows/storage-sftp-auto-enable.yaml
- .github/workflows/vm-auto-shutdown.yaml
- .github/workflows/vm-auto-start.yaml
- .github/workflows/vmss-auto-shutdown.yaml
- .github/workflows/vmss-auto-start.yaml
DUe to daylight saving & UTC, currently resources are stop/start one hour later than expected, similar PR was done last year - https://github.com/hmcts/auto-shutdown/pull/412/files
> Update crons following daylight saving change

- .github/ISSUE_TEMPLATE/config.yml
temp enable blank_issues_enabled for coding agent to get to work
> temp enable blank_issues_enabled

- .github/workflows/auto-start-status-check.yaml
- .github/workflows/auto-stop-status-check.yaml
- scripts/blob-storage/sftp-check-status.sh
- scripts/vm/common-functions.sh
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
> bypass vm if tag is databricks

- scripts/appgateway/common-functions.sh
- scripts/flexible-server/common-functions.sh
- scripts/vm/common-functions.sh
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
> update the environment tags

- scripts/flexible-server/common-functions.sh
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
> update flexi server tags

- scripts/aks/common-functions.sh
- scripts/appgateway/common-functions.sh
- scripts/bastion/common-functions.sh
- scripts/blob-storage/common-functions.sh
- scripts/sqlmi/common-functions.sh
- scripts/vm/common-functions.sh
- scripts/vmss/common-functions.sh
Re-add environments that were removed during recent changes
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
> Re-add missing envs

- .github/workflows/keepalive.yaml
https://tools.hmcts.net/jira/browse/DTSPO-26450
This PR updates the keepalive workflow to use `liskin/gh-workflow-keepalive@v1`, replacing the previously used (now suspended) `gautamkrishnar/keepalive-workflow@v2` action.
**Why?**
- The `gautamkrishnar/keepalive-workflow@v2` action has been suspended by GitHub due to the maintainer's account suspension, causing our keepalive workflows to fail completely.
- This workflow is critical for preventing GitHub from automatically disabling our scheduled workflows (like sandbox cleanup) after 60 days of repository inactivity.
**How the new changes work?**
- The new action is actively maintained, uses the GitHub API (no dummy commits), and requires only minimal permissions (actions: write).
- The `liskin/gh-workflow-keepalive@v1` action works by …
> DTSPO-26450 - migration of keepalive-workflow to gh-workflow-keepalive

- .github/workflows/mysql-flexible-auto-shutdown.yaml
- .github/workflows/mysql-flexible-auto-start.yaml
https://tools.hmcts.net/jira/browse/DTSPO-27462
Adding in production auto shutdown for mysql flexible server so long as auto-shutdown is set to true.
> Adds autoshut down for mysql prod env which correct tagging
